-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 18:38:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pegada_carbono
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pegada_carbono
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pegada_carbono` DEFAULT CHARACTER SET utf8 ;
USE `pegada_carbono` ;

-- -----------------------------------------------------
-- Table `pegada_carbono`.`colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegada_carbono`.`colaborador` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `habilitado` TINYINT NOT NULL,
  PRIMARY KEY (`idColaborador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pegada_carbono`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegada_carbono`.`veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(7) NOT NULL,
  `km_litro` DOUBLE NULL DEFAULT NULL,
  `disponivel` TINYINT NOT NULL,
  PRIMARY KEY (`idVeiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pegada_carbono`.`chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegada_carbono`.`chamado` (
  `idChamado` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `concluido` TINYINT NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `distancia` DOUBLE NOT NULL,
  `carbono` DOUBLE NULL DEFAULT NULL,
  `colaborador_idColaborador` INT NOT NULL,
  `veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idChamado`),
  INDEX `fk_chamado_colaborador_idx` (`colaborador_idColaborador` ASC) VISIBLE,
  INDEX `fk_chamado_veiculo1_idx` (`veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_chamado_colaborador`
    FOREIGN KEY (`colaborador_idColaborador`)
    REFERENCES `pegada_carbono`.`colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chamado_veiculo1`
    FOREIGN KEY (`veiculo_idVeiculo`)
    REFERENCES `pegada_carbono`.`veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
